package se.malmo.esb.primecase;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.2
 * Thu Oct 15 23:14:32 CEST 2009
 * Generated source version: 2.2.2
 * 
 */
 
@WebService(targetNamespace = "http://www.malmo.se/esb/primecase", name = "IHandleCase")
@XmlSeeAlso({org.tempuri.ObjectFactory.class,com.microsoft.schemas._2003._10.serialization.ObjectFactory.class,org.datacontract.schemas._2004._07.primesystems_primecasecore.ObjectFactory.class,com.microsoft.schemas._2003._10.serialization.arrays.ObjectFactory.class})
public interface IHandleCase {

    @WebResult(name = "GetRegistrationDraftsResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/IHandleCase/GetRegistrationDrafts", output = "http://tempuri.org/IHandleCase/GetRegistrationDraftsResponse", fault = {@FaultAction(className = IHandleCaseGetRegistrationDraftsAuthenticationModuleErrorFaultFaultMessage.class, value = "http://tempuri.org/IHandleCase/GetRegistrationDraftsAuthenticationModuleErrorFault"),@FaultAction(className = IHandleCaseGetRegistrationDraftsHandleCaseExceptionFaultFaultMessage.class, value = "http://tempuri.org/IHandleCase/GetRegistrationDraftsHandleCaseExceptionFault")})
    @RequestWrapper(localName = "GetRegistrationDrafts", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetRegistrationDrafts")
    @ResponseWrapper(localName = "GetRegistrationDraftsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetRegistrationDraftsResponse")
    @WebMethod(operationName = "GetRegistrationDrafts", action = "http://tempuri.org/IHandleCase/GetRegistrationDrafts")
    public org.datacontract.schemas._2004._07.primesystems_primecasecore.ArrayOfTempFormBasic getRegistrationDrafts(
        @WebParam(name = "authenticationInfo", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas._2004._07.primesystems_primecasecore.ContactAuthenticationInfo authenticationInfo
    ) throws IHandleCaseGetRegistrationDraftsAuthenticationModuleErrorFaultFaultMessage, IHandleCaseGetRegistrationDraftsHandleCaseExceptionFaultFaultMessage;

    @WebResult(name = "ChangeRegistrationFormResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/IHandleCase/ChangeRegistrationForm", output = "http://tempuri.org/IHandleCase/ChangeRegistrationFormResponse", fault = {@FaultAction(className = IHandleCaseChangeRegistrationFormAuthenticationModuleErrorFaultFaultMessage.class, value = "http://tempuri.org/IHandleCase/ChangeRegistrationFormAuthenticationModuleErrorFault"),@FaultAction(className = IHandleCaseChangeRegistrationFormHandleCaseExceptionFaultFaultMessage.class, value = "http://tempuri.org/IHandleCase/ChangeRegistrationFormHandleCaseExceptionFault")})
    @RequestWrapper(localName = "ChangeRegistrationForm", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ChangeRegistrationForm")
    @ResponseWrapper(localName = "ChangeRegistrationFormResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ChangeRegistrationFormResponse")
    @WebMethod(operationName = "ChangeRegistrationForm", action = "http://tempuri.org/IHandleCase/ChangeRegistrationForm")
    public org.datacontract.schemas._2004._07.primesystems_primecasecore.FormSavedReply changeRegistrationForm(
        @WebParam(name = "authenticationInfo", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas._2004._07.primesystems_primecasecore.ContactAuthenticationInfo authenticationInfo,
        @WebParam(name = "caseId", targetNamespace = "http://tempuri.org/")
        java.lang.Integer caseId,
        @WebParam(name = "form", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas._2004._07.primesystems_primecasecore.Form form,
        @WebParam(name = "signData", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas._2004._07.primesystems_primecasecore.SignData signData
    ) throws IHandleCaseChangeRegistrationFormAuthenticationModuleErrorFaultFaultMessage, IHandleCaseChangeRegistrationFormHandleCaseExceptionFaultFaultMessage;

    @WebResult(name = "RegisterCaseWithHandlerResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/IHandleCase/RegisterCaseWithHandler", output = "http://tempuri.org/IHandleCase/RegisterCaseWithHandlerResponse", fault = {@FaultAction(className = IHandleCaseRegisterCaseWithHandlerAuthenticationModuleErrorFaultFaultMessage.class, value = "http://tempuri.org/IHandleCase/RegisterCaseWithHandlerAuthenticationModuleErrorFault"),@FaultAction(className = IHandleCaseRegisterCaseWithHandlerHandleCaseExceptionFaultFaultMessage.class, value = "http://tempuri.org/IHandleCase/RegisterCaseWithHandlerHandleCaseExceptionFault")})
    @RequestWrapper(localName = "RegisterCaseWithHandler", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RegisterCaseWithHandler")
    @ResponseWrapper(localName = "RegisterCaseWithHandlerResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RegisterCaseWithHandlerResponse")
    @WebMethod(operationName = "RegisterCaseWithHandler", action = "http://tempuri.org/IHandleCase/RegisterCaseWithHandler")
    public org.datacontract.schemas._2004._07.primesystems_primecasecore.NewCaseReply registerCaseWithHandler(
        @WebParam(name = "authenticationInfo", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas._2004._07.primesystems_primecasecore.ContactAuthenticationInfo authenticationInfo,
        @WebParam(name = "caseTypeId", targetNamespace = "http://tempuri.org/")
        java.lang.Integer caseTypeId,
        @WebParam(name = "form", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas._2004._07.primesystems_primecasecore.Form form,
        @WebParam(name = "handlerGuid", targetNamespace = "http://tempuri.org/")
        java.lang.String handlerGuid,
        @WebParam(name = "handlerGroupGuid", targetNamespace = "http://tempuri.org/")
        java.lang.String handlerGroupGuid,
        @WebParam(name = "signData", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas._2004._07.primesystems_primecasecore.SignData signData
    ) throws IHandleCaseRegisterCaseWithHandlerAuthenticationModuleErrorFaultFaultMessage, IHandleCaseRegisterCaseWithHandlerHandleCaseExceptionFaultFaultMessage;

    @WebResult(name = "GetRequestedContactFieldsPrefilledResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/IHandleCase/GetRequestedContactFieldsPrefilled", output = "http://tempuri.org/IHandleCase/GetRequestedContactFieldsPrefilledResponse", fault = {@FaultAction(className = IHandleCaseGetRequestedContactFieldsPrefilledParameterErrorFaultFaultMessage.class, value = "http://tempuri.org/IHandleCase/GetRequestedContactFieldsPrefilledParameterErrorFault")})
    @RequestWrapper(localName = "GetRequestedContactFieldsPrefilled", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetRequestedContactFieldsPrefilled")
    @ResponseWrapper(localName = "GetRequestedContactFieldsPrefilledResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetRequestedContactFieldsPrefilledResponse")
    @WebMethod(operationName = "GetRequestedContactFieldsPrefilled", action = "http://tempuri.org/IHandleCase/GetRequestedContactFieldsPrefilled")
    public org.datacontract.schemas._2004._07.primesystems_primecasecore.ContactInfoInputs getRequestedContactFieldsPrefilled(
        @WebParam(name = "authenticationInfo", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas._2004._07.primesystems_primecasecore.ContactAuthenticationInfo authenticationInfo,
        @WebParam(name = "caseTypeId", targetNamespace = "http://tempuri.org/")
        java.lang.Integer caseTypeId
    ) throws IHandleCaseGetRequestedContactFieldsPrefilledParameterErrorFaultFaultMessage;

    @WebResult(name = "GetRequestedContactFieldsResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/IHandleCase/GetRequestedContactFields", output = "http://tempuri.org/IHandleCase/GetRequestedContactFieldsResponse", fault = {@FaultAction(className = IHandleCaseGetRequestedContactFieldsParameterErrorFaultFaultMessage.class, value = "http://tempuri.org/IHandleCase/GetRequestedContactFieldsParameterErrorFault")})
    @RequestWrapper(localName = "GetRequestedContactFields", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetRequestedContactFields")
    @ResponseWrapper(localName = "GetRequestedContactFieldsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetRequestedContactFieldsResponse")
    @WebMethod(operationName = "GetRequestedContactFields", action = "http://tempuri.org/IHandleCase/GetRequestedContactFields")
    public org.datacontract.schemas._2004._07.primesystems_primecasecore.ContactInfoInputs getRequestedContactFields(
        @WebParam(name = "caseTypeId", targetNamespace = "http://tempuri.org/")
        java.lang.Integer caseTypeId
    ) throws IHandleCaseGetRequestedContactFieldsParameterErrorFaultFaultMessage;

    @WebResult(name = "RegisterCaseWithHandlerAndContactDetailsResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/IHandleCase/RegisterCaseWithHandlerAndContactDetails", output = "http://tempuri.org/IHandleCase/RegisterCaseWithHandlerAndContactDetailsResponse", fault = {@FaultAction(className = IHandleCaseRegisterCaseWithHandlerAndContactDetailsAuthenticationModuleErrorFaultFaultMessage.class, value = "http://tempuri.org/IHandleCase/RegisterCaseWithHandlerAndContactDetailsAuthenticationModuleErrorFault"),@FaultAction(className = IHandleCaseRegisterCaseWithHandlerAndContactDetailsHandleCaseExceptionFaultFaultMessage.class, value = "http://tempuri.org/IHandleCase/RegisterCaseWithHandlerAndContactDetailsHandleCaseExceptionFault")})
    @RequestWrapper(localName = "RegisterCaseWithHandlerAndContactDetails", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RegisterCaseWithHandlerAndContactDetails")
    @ResponseWrapper(localName = "RegisterCaseWithHandlerAndContactDetailsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RegisterCaseWithHandlerAndContactDetailsResponse")
    @WebMethod(operationName = "RegisterCaseWithHandlerAndContactDetails", action = "http://tempuri.org/IHandleCase/RegisterCaseWithHandlerAndContactDetails")
    public org.datacontract.schemas._2004._07.primesystems_primecasecore.NewCaseReply registerCaseWithHandlerAndContactDetails(
        @WebParam(name = "authenticationInfo", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas._2004._07.primesystems_primecasecore.ContactAuthenticationInfo authenticationInfo,
        @WebParam(name = "contactInfo", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas._2004._07.primesystems_primecasecore.ContactInfo contactInfo,
        @WebParam(name = "caseTypeId", targetNamespace = "http://tempuri.org/")
        java.lang.Integer caseTypeId,
        @WebParam(name = "form", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas._2004._07.primesystems_primecasecore.Form form,
        @WebParam(name = "handlerGuid", targetNamespace = "http://tempuri.org/")
        java.lang.String handlerGuid,
        @WebParam(name = "handlerGroupGuid", targetNamespace = "http://tempuri.org/")
        java.lang.String handlerGroupGuid,
        @WebParam(name = "signData", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas._2004._07.primesystems_primecasecore.SignData signData
    ) throws IHandleCaseRegisterCaseWithHandlerAndContactDetailsAuthenticationModuleErrorFaultFaultMessage, IHandleCaseRegisterCaseWithHandlerAndContactDetailsHandleCaseExceptionFaultFaultMessage;

    @WebResult(name = "GetRegisteredFormResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/IHandleCase/GetRegisteredForm", output = "http://tempuri.org/IHandleCase/GetRegisteredFormResponse", fault = {@FaultAction(className = IHandleCaseGetRegisteredFormAuthenticationModuleErrorFaultFaultMessage.class, value = "http://tempuri.org/IHandleCase/GetRegisteredFormAuthenticationModuleErrorFault"),@FaultAction(className = IHandleCaseGetRegisteredFormGetRegistrationFormErrorFaultFaultMessage.class, value = "http://tempuri.org/IHandleCase/GetRegisteredFormGetRegistrationFormErrorFault"),@FaultAction(className = IHandleCaseGetRegisteredFormHandleCaseExceptionFaultFaultMessage.class, value = "http://tempuri.org/IHandleCase/GetRegisteredFormHandleCaseExceptionFault")})
    @RequestWrapper(localName = "GetRegisteredForm", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetRegisteredForm")
    @ResponseWrapper(localName = "GetRegisteredFormResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetRegisteredFormResponse")
    @WebMethod(operationName = "GetRegisteredForm", action = "http://tempuri.org/IHandleCase/GetRegisteredForm")
    public org.datacontract.schemas._2004._07.primesystems_primecasecore.Form getRegisteredForm(
        @WebParam(name = "authenticationInfo", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas._2004._07.primesystems_primecasecore.ContactAuthenticationInfo authenticationInfo,
        @WebParam(name = "caseId", targetNamespace = "http://tempuri.org/")
        java.lang.Integer caseId
    ) throws IHandleCaseGetRegisteredFormAuthenticationModuleErrorFaultFaultMessage, IHandleCaseGetRegisteredFormGetRegistrationFormErrorFaultFaultMessage, IHandleCaseGetRegisteredFormHandleCaseExceptionFaultFaultMessage;

    @WebResult(name = "GetRegistrationDraftResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/IHandleCase/GetRegistrationDraft", output = "http://tempuri.org/IHandleCase/GetRegistrationDraftResponse", fault = {@FaultAction(className = IHandleCaseGetRegistrationDraftAuthenticationModuleErrorFaultFaultMessage.class, value = "http://tempuri.org/IHandleCase/GetRegistrationDraftAuthenticationModuleErrorFault"),@FaultAction(className = IHandleCaseGetRegistrationDraftHandleCaseExceptionFaultFaultMessage.class, value = "http://tempuri.org/IHandleCase/GetRegistrationDraftHandleCaseExceptionFault"),@FaultAction(className = IHandleCaseGetRegistrationDraftGetTemporaryFormErrorFaultFaultMessage.class, value = "http://tempuri.org/IHandleCase/GetRegistrationDraftGetTemporaryFormErrorFault")})
    @RequestWrapper(localName = "GetRegistrationDraft", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetRegistrationDraft")
    @ResponseWrapper(localName = "GetRegistrationDraftResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetRegistrationDraftResponse")
    @WebMethod(operationName = "GetRegistrationDraft", action = "http://tempuri.org/IHandleCase/GetRegistrationDraft")
    public org.datacontract.schemas._2004._07.primesystems_primecasecore.Form getRegistrationDraft(
        @WebParam(name = "authenticationInfo", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas._2004._07.primesystems_primecasecore.ContactAuthenticationInfo authenticationInfo,
        @WebParam(name = "draftId", targetNamespace = "http://tempuri.org/")
        java.lang.String draftId
    ) throws IHandleCaseGetRegistrationDraftAuthenticationModuleErrorFaultFaultMessage, IHandleCaseGetRegistrationDraftHandleCaseExceptionFaultFaultMessage, IHandleCaseGetRegistrationDraftGetTemporaryFormErrorFaultFaultMessage;

    @WebResult(name = "DeleteRegistrationDraftResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/IHandleCase/DeleteRegistrationDraft", output = "http://tempuri.org/IHandleCase/DeleteRegistrationDraftResponse", fault = {@FaultAction(className = IHandleCaseDeleteRegistrationDraftAuthenticationModuleErrorFaultFaultMessage.class, value = "http://tempuri.org/IHandleCase/DeleteRegistrationDraftAuthenticationModuleErrorFault"),@FaultAction(className = IHandleCaseDeleteRegistrationDraftHandleCaseExceptionFaultFaultMessage.class, value = "http://tempuri.org/IHandleCase/DeleteRegistrationDraftHandleCaseExceptionFault")})
    @RequestWrapper(localName = "DeleteRegistrationDraft", targetNamespace = "http://tempuri.org/", className = "org.tempuri.DeleteRegistrationDraft")
    @ResponseWrapper(localName = "DeleteRegistrationDraftResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.DeleteRegistrationDraftResponse")
    @WebMethod(operationName = "DeleteRegistrationDraft", action = "http://tempuri.org/IHandleCase/DeleteRegistrationDraft")
    public org.datacontract.schemas._2004._07.primesystems_primecasecore.DeleteTempFormReply deleteRegistrationDraft(
        @WebParam(name = "authenticationInfo", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas._2004._07.primesystems_primecasecore.ContactAuthenticationInfo authenticationInfo,
        @WebParam(name = "draftId", targetNamespace = "http://tempuri.org/")
        java.lang.String draftId
    ) throws IHandleCaseDeleteRegistrationDraftAuthenticationModuleErrorFaultFaultMessage, IHandleCaseDeleteRegistrationDraftHandleCaseExceptionFaultFaultMessage;

    @WebResult(name = "RegisterCaseResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/IHandleCase/RegisterCase", output = "http://tempuri.org/IHandleCase/RegisterCaseResponse", fault = {@FaultAction(className = IHandleCaseRegisterCaseAuthenticationModuleErrorFaultFaultMessage.class, value = "http://tempuri.org/IHandleCase/RegisterCaseAuthenticationModuleErrorFault"),@FaultAction(className = IHandleCaseRegisterCaseHandleCaseExceptionFaultFaultMessage.class, value = "http://tempuri.org/IHandleCase/RegisterCaseHandleCaseExceptionFault")})
    @RequestWrapper(localName = "RegisterCase", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RegisterCase")
    @ResponseWrapper(localName = "RegisterCaseResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RegisterCaseResponse")
    @WebMethod(operationName = "RegisterCase", action = "http://tempuri.org/IHandleCase/RegisterCase")
    public org.datacontract.schemas._2004._07.primesystems_primecasecore.NewCaseReply registerCase(
        @WebParam(name = "authenticationInfo", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas._2004._07.primesystems_primecasecore.ContactAuthenticationInfo authenticationInfo,
        @WebParam(name = "caseTypeId", targetNamespace = "http://tempuri.org/")
        java.lang.Integer caseTypeId,
        @WebParam(name = "form", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas._2004._07.primesystems_primecasecore.Form form,
        @WebParam(name = "signData", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas._2004._07.primesystems_primecasecore.SignData signData
    ) throws IHandleCaseRegisterCaseAuthenticationModuleErrorFaultFaultMessage, IHandleCaseRegisterCaseHandleCaseExceptionFaultFaultMessage;

    @WebResult(name = "GetRegistrationFormResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/IHandleCase/GetRegistrationForm", output = "http://tempuri.org/IHandleCase/GetRegistrationFormResponse", fault = {@FaultAction(className = IHandleCaseGetRegistrationFormAuthenticationModuleErrorFaultFaultMessage.class, value = "http://tempuri.org/IHandleCase/GetRegistrationFormAuthenticationModuleErrorFault"),@FaultAction(className = IHandleCaseGetRegistrationFormGetRegistrationFormErrorFaultFaultMessage.class, value = "http://tempuri.org/IHandleCase/GetRegistrationFormGetRegistrationFormErrorFault"),@FaultAction(className = IHandleCaseGetRegistrationFormHandleCaseExceptionFaultFaultMessage.class, value = "http://tempuri.org/IHandleCase/GetRegistrationFormHandleCaseExceptionFault")})
    @RequestWrapper(localName = "GetRegistrationForm", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetRegistrationForm")
    @ResponseWrapper(localName = "GetRegistrationFormResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetRegistrationFormResponse")
    @WebMethod(operationName = "GetRegistrationForm", action = "http://tempuri.org/IHandleCase/GetRegistrationForm")
    public org.datacontract.schemas._2004._07.primesystems_primecasecore.Form getRegistrationForm(
        @WebParam(name = "authenticationInfo", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas._2004._07.primesystems_primecasecore.ContactAuthenticationInfo authenticationInfo,
        @WebParam(name = "caseTypeId", targetNamespace = "http://tempuri.org/")
        java.lang.Integer caseTypeId
    ) throws IHandleCaseGetRegistrationFormAuthenticationModuleErrorFaultFaultMessage, IHandleCaseGetRegistrationFormGetRegistrationFormErrorFaultFaultMessage, IHandleCaseGetRegistrationFormHandleCaseExceptionFaultFaultMessage;

    @WebResult(name = "GetUploadConstraintsResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/IHandleCase/GetUploadConstraints", output = "http://tempuri.org/IHandleCase/GetUploadConstraintsResponse", fault = {@FaultAction(className = IHandleCaseGetUploadConstraintsHandleCaseExceptionFaultFaultMessage.class, value = "http://tempuri.org/IHandleCase/GetUploadConstraintsHandleCaseExceptionFault")})
    @RequestWrapper(localName = "GetUploadConstraints", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetUploadConstraints")
    @ResponseWrapper(localName = "GetUploadConstraintsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetUploadConstraintsResponse")
    @WebMethod(operationName = "GetUploadConstraints", action = "http://tempuri.org/IHandleCase/GetUploadConstraints")
    public org.datacontract.schemas._2004._07.primesystems_primecasecore.UploadConstraints getUploadConstraints() throws IHandleCaseGetUploadConstraintsHandleCaseExceptionFaultFaultMessage;

    @WebResult(name = "GetCasesForContactResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/IHandleCase/GetCasesForContact", output = "http://tempuri.org/IHandleCase/GetCasesForContactResponse", fault = {@FaultAction(className = IHandleCaseGetCasesForContactAuthenticationModuleErrorFaultFaultMessage.class, value = "http://tempuri.org/IHandleCase/GetCasesForContactAuthenticationModuleErrorFault"),@FaultAction(className = IHandleCaseGetCasesForContactHandleCaseExceptionFaultFaultMessage.class, value = "http://tempuri.org/IHandleCase/GetCasesForContactHandleCaseExceptionFault")})
    @RequestWrapper(localName = "GetCasesForContact", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCasesForContact")
    @ResponseWrapper(localName = "GetCasesForContactResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCasesForContactResponse")
    @WebMethod(operationName = "GetCasesForContact", action = "http://tempuri.org/IHandleCase/GetCasesForContact")
    public org.datacontract.schemas._2004._07.primesystems_primecasecore.ArrayOfCaseInfoBasic getCasesForContact(
        @WebParam(name = "authenticationInfo", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas._2004._07.primesystems_primecasecore.ContactAuthenticationInfo authenticationInfo,
        @WebParam(name = "fromDate", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar fromDate,
        @WebParam(name = "activeCases", targetNamespace = "http://tempuri.org/")
        java.lang.Boolean activeCases,
        @WebParam(name = "completedCases", targetNamespace = "http://tempuri.org/")
        java.lang.Boolean completedCases
    ) throws IHandleCaseGetCasesForContactAuthenticationModuleErrorFaultFaultMessage, IHandleCaseGetCasesForContactHandleCaseExceptionFaultFaultMessage;

    @WebResult(name = "SaveRegistrationDraftResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/IHandleCase/SaveRegistrationDraft", output = "http://tempuri.org/IHandleCase/SaveRegistrationDraftResponse", fault = {@FaultAction(className = IHandleCaseSaveRegistrationDraftAuthenticationModuleErrorFaultFaultMessage.class, value = "http://tempuri.org/IHandleCase/SaveRegistrationDraftAuthenticationModuleErrorFault"),@FaultAction(className = IHandleCaseSaveRegistrationDraftHandleCaseExceptionFaultFaultMessage.class, value = "http://tempuri.org/IHandleCase/SaveRegistrationDraftHandleCaseExceptionFault")})
    @RequestWrapper(localName = "SaveRegistrationDraft", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SaveRegistrationDraft")
    @ResponseWrapper(localName = "SaveRegistrationDraftResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SaveRegistrationDraftResponse")
    @WebMethod(operationName = "SaveRegistrationDraft", action = "http://tempuri.org/IHandleCase/SaveRegistrationDraft")
    public java.lang.Boolean saveRegistrationDraft(
        @WebParam(name = "authenticationInfo", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas._2004._07.primesystems_primecasecore.ContactAuthenticationInfo authenticationInfo,
        @WebParam(name = "form", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas._2004._07.primesystems_primecasecore.Form form,
        @WebParam(name = "signText", targetNamespace = "http://tempuri.org/")
        java.lang.String signText
    ) throws IHandleCaseSaveRegistrationDraftAuthenticationModuleErrorFaultFaultMessage, IHandleCaseSaveRegistrationDraftHandleCaseExceptionFaultFaultMessage;

    @WebResult(name = "RegisterCaseWithContactDetailsResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/IHandleCase/RegisterCaseWithContactDetails", output = "http://tempuri.org/IHandleCase/RegisterCaseWithContactDetailsResponse", fault = {@FaultAction(className = IHandleCaseRegisterCaseWithContactDetailsAuthenticationModuleErrorFaultFaultMessage.class, value = "http://tempuri.org/IHandleCase/RegisterCaseWithContactDetailsAuthenticationModuleErrorFault"),@FaultAction(className = IHandleCaseRegisterCaseWithContactDetailsHandleCaseExceptionFaultFaultMessage.class, value = "http://tempuri.org/IHandleCase/RegisterCaseWithContactDetailsHandleCaseExceptionFault")})
    @RequestWrapper(localName = "RegisterCaseWithContactDetails", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RegisterCaseWithContactDetails")
    @ResponseWrapper(localName = "RegisterCaseWithContactDetailsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RegisterCaseWithContactDetailsResponse")
    @WebMethod(operationName = "RegisterCaseWithContactDetails", action = "http://tempuri.org/IHandleCase/RegisterCaseWithContactDetails")
    public org.datacontract.schemas._2004._07.primesystems_primecasecore.NewCaseReply registerCaseWithContactDetails(
        @WebParam(name = "authenticationInfo", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas._2004._07.primesystems_primecasecore.ContactAuthenticationInfo authenticationInfo,
        @WebParam(name = "contactInfo", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas._2004._07.primesystems_primecasecore.ContactInfo contactInfo,
        @WebParam(name = "caseTypeId", targetNamespace = "http://tempuri.org/")
        java.lang.Integer caseTypeId,
        @WebParam(name = "form", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas._2004._07.primesystems_primecasecore.Form form,
        @WebParam(name = "signData", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas._2004._07.primesystems_primecasecore.SignData signData
    ) throws IHandleCaseRegisterCaseWithContactDetailsAuthenticationModuleErrorFaultFaultMessage, IHandleCaseRegisterCaseWithContactDetailsHandleCaseExceptionFaultFaultMessage;

    @WebResult(name = "GetCaseResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/IHandleCase/GetCase", output = "http://tempuri.org/IHandleCase/GetCaseResponse", fault = {@FaultAction(className = IHandleCaseGetCaseAuthenticationModuleErrorFaultFaultMessage.class, value = "http://tempuri.org/IHandleCase/GetCaseAuthenticationModuleErrorFault"),@FaultAction(className = IHandleCaseGetCaseHandleCaseExceptionFaultFaultMessage.class, value = "http://tempuri.org/IHandleCase/GetCaseHandleCaseExceptionFault")})
    @RequestWrapper(localName = "GetCase", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCase")
    @ResponseWrapper(localName = "GetCaseResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCaseResponse")
    @WebMethod(operationName = "GetCase", action = "http://tempuri.org/IHandleCase/GetCase")
    public org.datacontract.schemas._2004._07.primesystems_primecasecore.CaseInfo getCase(
        @WebParam(name = "authInfo", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas._2004._07.primesystems_primecasecore.ContactAuthenticationInfo authInfo,
        @WebParam(name = "caseId", targetNamespace = "http://tempuri.org/")
        java.lang.Integer caseId
    ) throws IHandleCaseGetCaseAuthenticationModuleErrorFaultFaultMessage, IHandleCaseGetCaseHandleCaseExceptionFaultFaultMessage;
}
