
package se.malmo.esb.primecase;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.2.1
 * Mon Jun 15 17:24:05 CEST 2009
 * Generated source version: 2.2.1
 * 
 */

@WebFault(name = "GetRegistrationFormError", targetNamespace = "http://schemas.datacontract.org/2004/07/PrimeSystems.PrimeCaseCore.Portal")
public class IHandleCaseGetFormGetRegistrationFormErrorFaultFaultMessage extends Exception {
    public static final long serialVersionUID = 20090615172405L;
    
    private org.datacontract.schemas._2004._07.primesystems_primecasecore.GetRegistrationFormError getRegistrationFormError;

    public IHandleCaseGetFormGetRegistrationFormErrorFaultFaultMessage() {
        super();
    }
    
    public IHandleCaseGetFormGetRegistrationFormErrorFaultFaultMessage(String message) {
        super(message);
    }
    
    public IHandleCaseGetFormGetRegistrationFormErrorFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public IHandleCaseGetFormGetRegistrationFormErrorFaultFaultMessage(String message, org.datacontract.schemas._2004._07.primesystems_primecasecore.GetRegistrationFormError getRegistrationFormError) {
        super(message);
        this.getRegistrationFormError = getRegistrationFormError;
    }

    public IHandleCaseGetFormGetRegistrationFormErrorFaultFaultMessage(String message, org.datacontract.schemas._2004._07.primesystems_primecasecore.GetRegistrationFormError getRegistrationFormError, Throwable cause) {
        super(message, cause);
        this.getRegistrationFormError = getRegistrationFormError;
    }

    public org.datacontract.schemas._2004._07.primesystems_primecasecore.GetRegistrationFormError getFaultInfo() {
        return this.getRegistrationFormError;
    }
}
