
package se.malmo.esb.primecase;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.2.1
 * Mon Jun 15 17:24:05 CEST 2009
 * Generated source version: 2.2.1
 * 
 */

@WebFault(name = "GetTemporaryFormError", targetNamespace = "http://schemas.datacontract.org/2004/07/PrimeSystems.PrimeCaseCore.Portal")
public class IHandleCaseGetTempFormGetTemporaryFormErrorFaultFaultMessage extends Exception {
    public static final long serialVersionUID = 20090615172405L;
    
    private org.datacontract.schemas._2004._07.primesystems_primecasecore.GetTemporaryFormError getTemporaryFormError;

    public IHandleCaseGetTempFormGetTemporaryFormErrorFaultFaultMessage() {
        super();
    }
    
    public IHandleCaseGetTempFormGetTemporaryFormErrorFaultFaultMessage(String message) {
        super(message);
    }
    
    public IHandleCaseGetTempFormGetTemporaryFormErrorFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public IHandleCaseGetTempFormGetTemporaryFormErrorFaultFaultMessage(String message, org.datacontract.schemas._2004._07.primesystems_primecasecore.GetTemporaryFormError getTemporaryFormError) {
        super(message);
        this.getTemporaryFormError = getTemporaryFormError;
    }

    public IHandleCaseGetTempFormGetTemporaryFormErrorFaultFaultMessage(String message, org.datacontract.schemas._2004._07.primesystems_primecasecore.GetTemporaryFormError getTemporaryFormError, Throwable cause) {
        super(message, cause);
        this.getTemporaryFormError = getTemporaryFormError;
    }

    public org.datacontract.schemas._2004._07.primesystems_primecasecore.GetTemporaryFormError getFaultInfo() {
        return this.getTemporaryFormError;
    }
}
