
package se.malmo.esb.primecase;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.2.2
 * Thu Oct 15 23:14:32 CEST 2009
 * Generated source version: 2.2.2
 * 
 */

@WebFault(name = "GetRegistrationFormError", targetNamespace = "http://schemas.datacontract.org/2004/07/PrimeSystems.PrimeCaseCore.Portal")
public class IHandleCaseGetRegisteredFormGetRegistrationFormErrorFaultFaultMessage extends Exception {
    public static final long serialVersionUID = 20091015231432L;
    
    private org.datacontract.schemas._2004._07.primesystems_primecasecore.GetRegistrationFormError getRegistrationFormError;

    public IHandleCaseGetRegisteredFormGetRegistrationFormErrorFaultFaultMessage() {
        super();
    }
    
    public IHandleCaseGetRegisteredFormGetRegistrationFormErrorFaultFaultMessage(String message) {
        super(message);
    }
    
    public IHandleCaseGetRegisteredFormGetRegistrationFormErrorFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public IHandleCaseGetRegisteredFormGetRegistrationFormErrorFaultFaultMessage(String message, org.datacontract.schemas._2004._07.primesystems_primecasecore.GetRegistrationFormError getRegistrationFormError) {
        super(message);
        this.getRegistrationFormError = getRegistrationFormError;
    }

    public IHandleCaseGetRegisteredFormGetRegistrationFormErrorFaultFaultMessage(String message, org.datacontract.schemas._2004._07.primesystems_primecasecore.GetRegistrationFormError getRegistrationFormError, Throwable cause) {
        super(message, cause);
        this.getRegistrationFormError = getRegistrationFormError;
    }

    public org.datacontract.schemas._2004._07.primesystems_primecasecore.GetRegistrationFormError getFaultInfo() {
        return this.getRegistrationFormError;
    }
}
