
package se.malmo.esb.primecase;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.2.2
 * Thu Oct 15 23:14:32 CEST 2009
 * Generated source version: 2.2.2
 * 
 */

@WebFault(name = "ParameterError", targetNamespace = "http://schemas.datacontract.org/2004/07/PrimeSystems.PrimeCaseCore.Portal")
public class IHandleCaseGetRequestedContactFieldsParameterErrorFaultFaultMessage extends Exception {
    public static final long serialVersionUID = 20091015231432L;
    
    private org.datacontract.schemas._2004._07.primesystems_primecasecore.ParameterError parameterError;

    public IHandleCaseGetRequestedContactFieldsParameterErrorFaultFaultMessage() {
        super();
    }
    
    public IHandleCaseGetRequestedContactFieldsParameterErrorFaultFaultMessage(String message) {
        super(message);
    }
    
    public IHandleCaseGetRequestedContactFieldsParameterErrorFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public IHandleCaseGetRequestedContactFieldsParameterErrorFaultFaultMessage(String message, org.datacontract.schemas._2004._07.primesystems_primecasecore.ParameterError parameterError) {
        super(message);
        this.parameterError = parameterError;
    }

    public IHandleCaseGetRequestedContactFieldsParameterErrorFaultFaultMessage(String message, org.datacontract.schemas._2004._07.primesystems_primecasecore.ParameterError parameterError, Throwable cause) {
        super(message, cause);
        this.parameterError = parameterError;
    }

    public org.datacontract.schemas._2004._07.primesystems_primecasecore.ParameterError getFaultInfo() {
        return this.parameterError;
    }
}
