
package se.malmo.esb.primecase;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.2.1
 * Mon Jun 15 17:24:05 CEST 2009
 * Generated source version: 2.2.1
 * 
 */

@WebFault(name = "ParameterError", targetNamespace = "http://schemas.datacontract.org/2004/07/PrimeSystems.PrimeCaseCore.Portal")
public class IHandleCaseGetContactInfoInputsParameterErrorFaultFaultMessage extends Exception {
    public static final long serialVersionUID = 20090615172405L;
    
    private org.datacontract.schemas._2004._07.primesystems_primecasecore.ParameterError parameterError;

    public IHandleCaseGetContactInfoInputsParameterErrorFaultFaultMessage() {
        super();
    }
    
    public IHandleCaseGetContactInfoInputsParameterErrorFaultFaultMessage(String message) {
        super(message);
    }
    
    public IHandleCaseGetContactInfoInputsParameterErrorFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public IHandleCaseGetContactInfoInputsParameterErrorFaultFaultMessage(String message, org.datacontract.schemas._2004._07.primesystems_primecasecore.ParameterError parameterError) {
        super(message);
        this.parameterError = parameterError;
    }

    public IHandleCaseGetContactInfoInputsParameterErrorFaultFaultMessage(String message, org.datacontract.schemas._2004._07.primesystems_primecasecore.ParameterError parameterError, Throwable cause) {
        super(message, cause);
        this.parameterError = parameterError;
    }

    public org.datacontract.schemas._2004._07.primesystems_primecasecore.ParameterError getFaultInfo() {
        return this.parameterError;
    }
}
