
package se.malmo.esb.primecase;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.2.2
 * Thu Oct 15 23:14:32 CEST 2009
 * Generated source version: 2.2.2
 * 
 */

@WebFault(name = "GetTemporaryFormError", targetNamespace = "http://schemas.datacontract.org/2004/07/PrimeSystems.PrimeCaseCore.Portal")
public class IHandleCaseGetRegistrationDraftGetTemporaryFormErrorFaultFaultMessage extends Exception {
    public static final long serialVersionUID = 20091015231432L;
    
    private org.datacontract.schemas._2004._07.primesystems_primecasecore.GetTemporaryFormError getTemporaryFormError;

    public IHandleCaseGetRegistrationDraftGetTemporaryFormErrorFaultFaultMessage() {
        super();
    }
    
    public IHandleCaseGetRegistrationDraftGetTemporaryFormErrorFaultFaultMessage(String message) {
        super(message);
    }
    
    public IHandleCaseGetRegistrationDraftGetTemporaryFormErrorFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public IHandleCaseGetRegistrationDraftGetTemporaryFormErrorFaultFaultMessage(String message, org.datacontract.schemas._2004._07.primesystems_primecasecore.GetTemporaryFormError getTemporaryFormError) {
        super(message);
        this.getTemporaryFormError = getTemporaryFormError;
    }

    public IHandleCaseGetRegistrationDraftGetTemporaryFormErrorFaultFaultMessage(String message, org.datacontract.schemas._2004._07.primesystems_primecasecore.GetTemporaryFormError getTemporaryFormError, Throwable cause) {
        super(message, cause);
        this.getTemporaryFormError = getTemporaryFormError;
    }

    public org.datacontract.schemas._2004._07.primesystems_primecasecore.GetTemporaryFormError getFaultInfo() {
        return this.getTemporaryFormError;
    }
}
